title: "Daniel Burgos's Portfolio"
author: "Daniel Burgos"
description: "Data is Power"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Portfolio", icon: home}
  - {file: "README.md", title: "Data Analytics", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:daniebm92@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/daniebm"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/daniel-burgos-1b768934/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
